version: 0.2

phases:
  post_build:
    commands:
      - echo $INSTANCE_ID
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/my-web-app.war
  discard-paths: yes
